FROM debian:bookworm AS base
ENV DEBIAN_FRONTEND=noninteractive
RUN <<EOF
    apt update 
    apt full-upgrade 
    apt install -y appstream build-essential cimg-dev cmake curl desktop-file-utils file fuse3 git libass-dev \
        libavcodec-dev libboost-filesystem-dev libcurl4-openssl-dev libfribidi-dev \
        libfuse2 libfuse3-3 libfuse3-dev libfuse-dev libgcrypt-dev libgles1 libgles2 libgles-dev \
        libglib2.0-dev libglvnd-core-dev libglvnd-dev libgpgme-dev libjpeg-dev libpng-dev libpulse-dev \
        libsdl2-dev libsquashfuse0 libsquashfuse-dev libx11-xcb-dev mesa-common-dev nasm patchelf pkg-config \
        qtbase5-dev squashfs-tools squashfuse wget zlib1g-dev zsync libevdev-dev qt6-base-dev qt6-svg-dev qt6-base-private-dev
    rm -rf /var/lib/apt/lists/*
EOF

FROM base AS appimagetool
RUN <<EOF
    mkdir /git /staging

    git clone \
        https://github.com/AppImage/appimagetool.git \
        /git/appimagetool

    cd /git/appimagetool
    git reset --hard 8c8c91f7 # Release 1.9.1
    cmake -B _build -DCMAKE_INSTALL_PREFIX=/usr .
    cmake --build _build -j$(nproc)
    DESTDIR=/staging cmake --install _build
EOF

FROM base AS linuxdeploy-and-plug
RUN <<EOF
    mkdir /git /staging

    git clone \
        https://github.com/linuxdeploy/linuxdeploy.git \
        /git/linuxdeploy

    git clone \
        https://github.com/linuxdeploy/linuxdeploy-plugin-appimage.git \
        /git/linuxdeploy-plugin-appimage \

    git clone \
        https://github.com/linuxdeploy/linuxdeploy-plugin-qt.git \
        /git/linuxdeploy-plugin-qt

    cd /git/linuxdeploy
    git reset --hard cc7b8647 # Release 1-alpha-20251107-1
    git submodule update --init --recursive --depth 1
    cmake -B _build -DCMAKE_INSTALL_PREFIX=/usr .
    cmake --build _build -j$(nproc)
    DESTDIR=/staging cmake --install _build

    cd /git/linuxdeploy-plugin-appimage
    git reset --hard 96502d15 # Release 1-alpha-20250213-1
    git submodule update --init --recursive --depth 1
    cmake -B _build -DCMAKE_INSTALL_PREFIX=/usr .
    cmake --build _build -j$(nproc)
    DESTDIR=/staging cmake --install _build

    cd /git/linuxdeploy-plugin-qt
    git reset --hard ce5291e2 # Release 1-alpha-20250213-1
    git submodule update --init --recursive --depth 1
    cmake -B _build -DCMAKE_INSTALL_PREFIX=/usr .
    cmake --build _build -j$(nproc)
    DESTDIR=/staging cmake --install _build
EOF

FROM base
COPY --from=appimagetool /staging /
COPY --from=linuxdeploy-and-plug /staging /

#ENTRYPOINT ["/bin/sh", "-c", "cd /res/scripts; ./build.sh"]

